name: BankNotes
main: AndreasHGK\BankNotes\Main
version: 1.0.2
api: [3.0.0-ALPHA12, 3.0.0]
load: POSTWORLD
author: AndreasHGK
softdepend: ["EconomyAPI"]

commands:
 note:
  description: ""
  usage: "/note {amount}"
  aliases: ["withdraw"]
  permission: banknotes.get
 banknote:
  description: ""
  usage: "/banknote {amount}"
  permission: banknotes.get
 banknotes:
  description: ""
  usage: "/banknotes {amount}"
  permission: banknotes.get
 deposit:
  description: ""
  usage: "/deposit"
  permission: banknotes.deposit

permissions:
 banknotes:
  default: true
  description: ""
  children:
   banknotes.get:
    default: true
    description: ""
   banknotes.deposit:
    default: true
    description: ""
